### ISSUE TITLE
dbus-mqtt errors on the demo mode

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#265]
To reproduce, enable dbus-mqtt and the demo mode. Strangely it seems to only crash on the tank data coming from the demo mode: No errors when the tanks are removed from play.sh.

Perhaps the recording was made when dbus-adc was flaky, and fixed by making a new recording?

dbus-mqtt log:
```
2018-02-19 20:45:12.288761500 INFO:dbus_mqtt:[Scanning] service: com.victronenergy.tank.tty31
2018-02-19 20:45:12.312900500 Traceback (most recent call last):
2018-02-19 20:45:12.319339500   File "/opt/victronenergy/dbus-mqtt/dbus_mqtt.py", line 343, in <module>
2018-02-19 20:45:12.319370500     init_broker=args.init_broker)
2018-02-19 20:45:12.319370500   File "/opt/victronenergy/dbus-mqtt/dbus_mqtt.py", line 64, in __init__
2018-02-19 20:45:12.319370500     self._scan_dbus_service(service, publish=False)
2018-02-19 20:45:12.319370500   File "/opt/victronenergy/dbus-mqtt/dbus_mqtt.py", line 193, in _scan_dbus_service
2018-02-19 20:45:12.319400500     items = self._get_dbus_value(service, '/')
2018-02-19 20:45:12.321079500   File "/opt/victronenergy/dbus-mqtt/dbus_mqtt.py", line 273, in _get_dbus_value
2018-02-19 20:45:12.321109500     value = self._dbus_conn.call_blocking(service, path, None, 'GetValue', '', [])
2018-02-19 20:45:12.321109500   File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
2018-02-19 20:45:12.340702500     message, timeout)
2018-02-19 20:45:12.340702500 dbus.exceptions.DBusException: org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
2018-02-19 20:45:12.340702500   File "/usr/lib/python2.7/site-packages/dbus/service.py", line 751, in _message_cb
2018-02-19 20:45:12.340732500     _method_reply_return(connection, message, method_name, signature, *retval)
2018-02-19 20:45:12.340732500   File "/usr/lib/python2.7/site-packages/dbus/service.py", line 254, in _method_reply_return
2018-02-19 20:45:12.342777500     reply.append(signature=signature, *retval)
2018-02-19 20:45:12.342777500 TypeError: an integer is required
```

error on console when starting demo mode from there:
```
ERROR:dbus.service:Unable to append

(dbus.Dictionary({  
   dbus.String(u'Dummy'):dbus.Int32(1784),
   dbus.String(u'HardwareVersion'):dbus.Int32(0),
   dbus.String(u'Capacity'):dbus.Int32(100),
   dbus.String(u'Level'):dbus.Int32(85),
   dbus.String(u'DeviceInstance'):dbus.Int32(231),
   dbus.String(u'Remaining'):dbus.Int32(85),
   dbus.String(u'ProductName'):dbus.String(u'Tank sensor'),
   dbus.String(u'Connected'):dbus.Int32(1),
   dbus.String(u'Mgmt/ProcessVersion'):dbus.String(u'Unkown version, and running on Python 2.7.3'),
   dbus.String(u'FluidType'):dbus.Int32(5),
   dbus.String(u'Mgmt/ProcessName'):dbus.String(u'./../ext/velib_python/dbusdummyservice.pyo'),
   dbus.String(u'Mgmt/Connection'):dbus.String(u'Dummy service'),
   dbus.String(u'FirmwareVersion'):dbus.Int32(0),
   dbus.String(u'ProductId'):dbus.Int32(0)
},
signature=None),
)

to message with signature v: <type 'exceptions.TypeError'>: an integer is required
```

**Comment by jepefe** [comment]
Problem here is that recordings were made from a dummy device and dbus-mqtt crashes when doing GetValue on "/" because the tank service throws an unexpected error.
Fixed by creating new recordings from a real tank sender. https://github.com/victronenergy/dbus-recorder/commit/a40adc0a1eb57d1979acc26943fb602ee5c84e73
