### ISSUE TITLE
mqtt-rpc errors on weird serial number

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#268]
Seen on Almere MPPT ESS, it (for some yet unknown reason) has a BMV-712 connected to it with a weird serial number.

Error:
```
2018-02-25 09:23:12.016179500 Exception in thread Thread-3:
2018-02-25 09:23:12.016195500 Traceback (most recent call last):
2018-02-25 09:23:12.016202500   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2018-02-25 09:23:12.016211500     self.run()
2018-02-25 09:23:12.016217500   File "/usr/lib/python2.7/threading.py", line 763, in run
2018-02-25 09:23:12.016225500     self.__target(*self.__args, **self.__kwargs)
2018-02-25 09:23:12.016232500   File "/opt/victronenergy/mqtt-rpc/./ext/velib_python/streamcommand.py", line 40, in target
2018-02-25 09:23:12.017831500     self.readandsend()
2018-02-25 09:23:12.017840500   File "/opt/victronenergy/mqtt-rpc/./ext/velib_python/streamcommand.py", line 82, in readandsend
2018-02-25 09:23:12.017850500     self.feedbacksender.send({"status": "running", "xmloutput": line})
2018-02-25 09:23:12.017858500   File "/opt/victronenergy/mqtt-rpc/mqtt-rpc.py", line 147, in send
2018-02-25 09:23:12.017867500     payload = json.dumps(a)
2018-02-25 09:23:12.019025500   File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
2018-02-25 09:23:12.019036500     return _default_encoder.encode(obj)
2018-02-25 09:23:12.019043500   File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
2018-02-25 09:23:12.019051500     chunks = self.iterencode(o, _one_shot=True)
2018-02-25 09:23:12.019058500   File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
2018-02-25 09:23:12.019066500     return _iterencode(o, 0)
2018-02-25 09:23:12.020155500 UnicodeDecodeError: 'utf8' codec can't decode byte 0xd0 in position 35: invalid continuation byte
```

Input into mqtt-rpc:
```
# /opt/victronenergy/serial-starter/stop-tty.sh /dev/ttyO0
# dup -s "/dev/ttyO0 /dev/ttyO2" -x
<?xml version="1.0" encoding="UTF-8"?>
<duprun version="1.0.16">
<discovered>
<device port="/dev/ttyO0" serial="2Ðð" mode="app" description="BMV-712 Smart" id="A381" version="4.00" versionAsDecimal="1024" updatable="True" settingsMigration="True"></device>
<device port="/dev/ttyO2" serial="HQ15242G34T" mode="app" description="BlueSolar Charger MPPT 150/60" id="A04E" version="1.29" versionAsDecimal="297" updatable="True" settingsMigration="True"></device>
</discovered>
</duprun>

# /opt/victronenergy/serial-starter/start-tty.sh /dev/ttyO0
```

printing the variable before loading it into json.dumps shows:
```
{'ts': 1519550591, 'opResponse': {'msgnr': 5, 'finished': False, 'command': 'duplist', 'feedback': {'status': 'running', 'xmloutput': '<device port="/dev/ttyO0" serial="2\xd0\xf0" mode="app" description="BMV-712 Smart" id="A381" version="4.00" versionAsDecimal="1024" updatable="True" settingsMigration="True"></device>\n'}, 'commandid': u'tnqctN0E'}}
```

Most likely it has something to do with character encoding; not my specialty.

Not so sure if we should actually fix this. Lets first see where that BMV is coming from (normal production or R&D)

**Comment by mpvader** [comment]
Changing the encoding from the default utg-8 to latin-1 also fixes it: j = json.dumps(a, encoding="latin-1").

results in this json string:
```
'{"ts": 1519550591, "opResponse": {"commandid": "tnqctN0E", "msgnr": 5, "command": "duplist", "finished": false, "feedback": {"status": "running", "xmloutput": "<device port=\\"/dev/ttyO0\\" serial=\\"2\\u00d0\\u00f0\\" mode=\\"app\\" description=\\"BMV-712 Smart\\" id=\\"A381\\" version=\\"4.00\\" versionAsDecimal=\\"1024\\" updatable=\\"True\\" settingsMigration=\\"True\\"></device>\\n"}}}'
```
