### ISSUE TITLE
mqtt-rpc: dbusmonitor error during veconfigure read

### ISSUE THREAD

**Issue by vejpasop** [victronenergy/venus#275]
Seen on CCGX of Jos. Running `v2.20~21`, mqtt-rpc v1.06. The error is not showing up on v2.20~19, mqtt-rpc v1.05. Perhaps a regression of the velib upgrade?

Note that the error doesnt seem to hurt the process: there is still a file download showing up in the browser.

```
2018-04-10 07:16:20.874693500 INFO:__main__:Ping received, sending pong back
2018-04-10 07:16:22.151410500 INFO:__main__:Starting mk2VscThread
2018-04-10 07:16:22.169941500 INFO:vrmmk2vsc:read_settings
2018-04-10 07:16:22.306998500 INFO:dbusmonitor:Found: com.victronenergy.mk2vsc, scanning and storing items
2018-04-10 07:16:22.670642500 ERROR:dbusmonitor:Ignoring com.victronenergy.mk2vsc because of error while scanning:
2018-04-10 07:16:22.686852500 Traceback (most recent call last):
2018-04-10 07:16:22.688770500   File "/opt/victronenergy/mqtt-rpc/./ext/velib_python/dbusmonitor.py", line 114, in scan_dbus_service
2018-04-10 07:16:22.690785500     return self.scan_dbus_service_inner(serviceName)
2018-04-10 07:16:22.695100500   File "/opt/victronenergy/mqtt-rpc/./ext/velib_python/dbusmonitor.py", line 166, in scan_dbus_service_inner
2018-04-10 07:16:22.695119500     None, 'GetValue', '', [])
2018-04-10 07:16:22.695126500   File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
2018-04-10 07:16:22.695135500     message, timeout)
2018-04-10 07:16:22.695141500 DBusException: org.freedesktop.DBus.Error.UnknownObject: org.freedesktop.DBus.Error.UnknownObject
2018-04-10 07:17:13.727002500 INFO:__main__:Filedownload announce received. Starting file sender
2018-04-10 07:17:13.731470500 INFO:__main__:Exiting mk2VscThread
2018-04-10 07:17:13.760841500 INFO:file_mgmt:FileSender initialized. Sending '/data/vrmfilescache/a0f6fd5b5893_inst_ttyO1_Interfaces_Mk2_Tunnel.rvms' in 1 chunks
2018-04-10 07:17:13.877078500 INFO:file_mgmt:Chunk 0 acked by remote. That makes for the complete file.
2018-04-10 07:17:13.890456500 INFO:file_mgmt:FileSender object done, marking as expired
```

**Comment by izak** [comment]
It's a device without a `/DeviceInstance`. A little over a year ago we made it ignore these and just assume the DeviceInstance is zero. Then we fixed that overly bad assumption and caused this one. So what is `com.victronenergy.mk2vsc`? Does it need fixing?

**Comment by izak** [comment]
Yes, it needs fixing. It is not harmless. It breaks downloading of the Multi config.

**Comment by vejpasop** [comment]
`com.victronenergy.mk2vsc` is the process that reads and writes the multi configuration.  This process communicates with the Multi through `com.victronenergy.vebus.tty##/Interfaces/Mk2/Tunnel` 

What is the definition of `/DeviceInstance` and why do we need it for mk2vsc?

**Comment by izak** [comment]
The Victron dbus spec requires services to have a `/DeviceInstance`, but I think this is only required of actual pieces of hardware. We have a few exceptions in the code for services that don't have it (`com.victronenergy.settings` for example) and I just had to know if this is one.

But this opens up a larger question: Should we be able to monitor such things with dbusmonitor? Other services that don't have a DeviceInstance are:

`com.victronenergy.fronius` (the pv-inverters spawned by this one are okay though).
`com.victronenergy.hub4` (deprecated in any case)
`com.victronenergy.logger`
`com.victronenergy.settings` (dbusmonitor hardcodes DeviceInstance as 0)
`com.victronenergy.vecan.canX`

These are services that don't come and go, so I am inclined to say that we keep the status quo: Ignore them, just be less stack-trace-loggy about it.

**Comment by mpvader** [comment]
Indeed; these services do not need monitoring with dbusmonitor.

**Comment by mpvader** [comment]
Venus v2.20~22
