### ISSUE TITLE
Traceback when someone turns on DVCC and the firmware on the solar charger is too old

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#277]
Ideally we should fail gracefully and not like this.

```
2018-04-10 14:37:23.339578500 -------- dbus_systemcalc, v1.52 is starting up --------
2018-04-10 14:37:23.345996500 INFO:logger:Loglevel set to INFO
2018-04-10 14:37:23.439804500 INFO:dbusmonitor:===== Search on dbus for services that we will monitor starting... =====
2018-04-10 14:37:23.449500500 INFO:dbusmonitor:Found: com.victronenergy.solarcharger.ttyO2, scanning and storing items
2018-04-10 14:37:23.472355500 INFO:dbusmonitor:       com.victronenergy.solarcharger.ttyO2 has device instance 258
2018-04-10 14:37:23.551364500 INFO:dbusmonitor:Found: com.victronenergy.vecan.can0, scanning and storing items
2018-04-10 14:37:23.572279500 INFO:dbusmonitor:       com.victronenergy.vecan.can0 has device instance 0
2018-04-10 14:37:23.584966500 INFO:dbusmonitor:Found: com.victronenergy.vebus.ttyO1, scanning and storing items
2018-04-10 14:37:23.603126500 INFO:dbusmonitor:       com.victronenergy.vebus.ttyO1 has device instance 257
2018-04-10 14:37:23.751822500 INFO:dbusmonitor:Found: com.victronenergy.settings, scanning and storing items
2018-04-10 14:37:23.765335500 INFO:dbusmonitor:       com.victronenergy.settings has device instance 0
2018-04-10 14:37:23.862855500 INFO:dbusmonitor:Found: com.victronenergy.battery.socketcan_can0_di0_uc1376305, scanning and storing items
2018-04-10 14:37:23.874784500 INFO:dbusmonitor:       com.victronenergy.battery.socketcan_can0_di0_uc1376305 has device instance 0
2018-04-10 14:37:23.932019500 INFO:dbusmonitor:===== Search on dbus for services that we will monitor finished =====
2018-04-10 14:37:24.676286500 INFO:vedbus:registered ourselves on D-Bus as com.victronenergy.system
2018-04-10 14:37:24.727613500 INFO:relaystate:Relays found: /dev/gpio/relay_1/value
2018-04-10 14:37:24.739277500 INFO:buzzercontrol:GPIO buzzer found: /sys/class/gpio/gpio35/value
2018-04-10 14:37:25.064834500 INFO:dbus_systemcalc:Battery service, setting == com.victronenergy.battery/0, changed from None to com.victronenergy.battery.socketcan_can0_di0_uc1376305 (0)
2018-04-10 14:37:25.338819500 INFO:dbus_systemcalc:Starting mainloop, responding only on events
2018-04-10 14:37:28.150674500 exit_on_error: there was an exception. Printing stacktrace will be tryed and then exit
2018-04-10 14:37:28.152988500 Traceback (most recent call last):
2018-04-10 14:37:28.166815500   File "/opt/victronenergy/dbus-systemcalc-py/ext/velib_python/ve_utils.py", line 19, in exit_on_error
2018-04-10 14:37:28.166836500     return func(*args, **kwargs)
2018-04-10 14:37:28.168959500   File "/opt/victronenergy/dbus-systemcalc-py/delegates/dvcc.py", line 657, in _on_timer
2018-04-10 14:37:28.175314500     bms_service, _max_charge_current)
2018-04-10 14:37:28.187943500   File "/opt/victronenergy/dbus-systemcalc-py/delegates/dvcc.py", line 753, in _update_solarchargers
2018-04-10 14:37:28.194870500     charge_voltage, max_charge_current, feedback_allowed)
2018-04-10 14:37:28.216928500   File "/opt/victronenergy/dbus-systemcalc-py/delegates/dvcc.py", line 266, in set_networked
2018-04-10 14:37:28.216950500     sc.maxchargecurrent = cc
2018-04-10 14:37:28.248810500   File "/opt/victronenergy/dbus-systemcalc-py/delegates/dvcc.py", line 116, in maxchargecurrent
2018-04-10 14:37:28.248832500     self._set_path('/Link/ChargeCurrent', v)
2018-04-10 14:37:28.248969500   File "/opt/victronenergy/dbus-systemcalc-py/delegates/dvcc.py", line 86, in _set_path
2018-04-10 14:37:28.249024500     self.monitor.set_value(self.service, path, v)
2018-04-10 14:37:28.249231500   File "/opt/victronenergy/dbus-systemcalc-py/ext/velib_python/dbusmonitor.py", line 269, in set_value
2018-04-10 14:37:28.269592500     args=[wrap_dbus_value(value)])
2018-04-10 14:37:28.280488500   File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
2018-04-10 14:37:28.295826500     message, timeout)
2018-04-10 14:37:28.310980500 DBusException: org.freedesktop.DBus.Error.UnknownObject: org.freedesktop.DBus.Error.UnknownObject
2018-04-10 14:37:31.112177500 -------- dbus_systemcalc, v1.52 is starting up --------
2018-04-10 14:37:31.127632500 INFO:logger:Loglevel set to INFO
2018-04-10 14:37:31.311409500 INFO:dbusmonitor:===== Search on dbus for services that we will monitor starting... =====
2018-04-10 14:37:31.321557500 INFO:dbusmonitor:Found: com.victronenergy.solarcharger.ttyO2, scanning and storing items
2018-04-10 14:37:31.342066500 INFO:dbusmonitor:       com.victronenergy.solarcharger.ttyO2 has device instance 258
2018-04-10 14:37:31.430255500 INFO:dbusmonitor:Found: com.victronenergy.vecan.can0, scanning and storing items
2018-04-10 14:37:31.461791500 INFO:dbusmonitor:       com.victronenergy.vecan.can0 has device instance 0
2018-04-10 14:37:31.492087500 INFO:dbusmonitor:Found: com.victronenergy.vebus.ttyO1, scanning and storing items
2018-04-10 14:37:31.511309500 INFO:dbusmonitor:       com.victronenergy.vebus.ttyO1 has device instance 257
2018-04-10 14:37:31.663680500 INFO:dbusmonitor:Found: com.victronenergy.settings, scanning and storing items
2018-04-10 14:37:31.676024500 INFO:dbusmonitor:       com.victronenergy.settings has device instance 0
2018-04-10 14:37:31.764234500 INFO:dbusmonitor:Found: com.victronenergy.battery.socketcan_can0_di0_uc1376305, scanning and storing items
2018-04-10 14:37:31.774606500 INFO:dbusmonitor:       com.victronenergy.battery.socketcan_can0_di0_uc1376305 has device instance 0
2018-04-10 14:37:31.833573500 INFO:dbusmonitor:===== Search on dbus for services that we will monitor finished =====
2018-04-10 14:37:32.490908500 INFO:vedbus:registered ourselves on D-Bus as com.victronenergy.system
2018-04-10 14:37:32.562154500 INFO:relaystate:Relays found: /dev/gpio/relay_1/value
2018-04-10 14:37:32.578924500 INFO:buzzercontrol:GPIO buzzer found: /sys/class/gpio/gpio35/value
2018-04-10 14:37:32.851639500 INFO:dbus_systemcalc:Battery service, setting == com.victronenergy.battery/0, changed from None to com.victronenergy.battery.socketcan_can0_di0_uc1376305 (0)
2018-04-10 14:37:33.125573500 INFO:dbus_systemcalc:Starting mainloop, responding only on events
2018-04-10 14:37:35.988911500 exit_on_error: there was an exception. Printing stacktrace will be tryed and then exit
2018-04-10 14:37:35.991002500 Traceback (most recent call last):
2018-04-10 14:37:35.996751500   File "/opt/victronenergy/dbus-systemcalc-py/ext/velib_python/ve_utils.py", line 19, in exit_on_error
2018-04-10 14:37:35.996770500     return func(*args, **kwargs)
2018-04-10 14:37:35.996776500   File "/opt/victronenergy/dbus-systemcalc-py/delegates/dvcc.py", line 657, in _on_timer
2018-04-10 14:37:36.008692500     bms_service, _max_charge_current)
2018-04-10 14:37:36.017144500   File "/opt/victronenergy/dbus-systemcalc-py/delegates/dvcc.py", line 753, in _update_solarchargers
2018-04-10 14:37:36.019712500     charge_voltage, max_charge_current, feedback_allowed)
2018-04-10 14:37:36.026749500   File "/opt/victronenergy/dbus-systemcalc-py/delegates/dvcc.py", line 266, in set_networked
2018-04-10 14:37:36.026768500     sc.maxchargecurrent = cc
2018-04-10 14:37:36.026775500   File "/opt/victronenergy/dbus-systemcalc-py/delegates/dvcc.py", line 116, in maxchargecurrent
2018-04-10 14:37:36.026784500     self._set_path('/Link/ChargeCurrent', v)
2018-04-10 14:37:36.026791500   File "/opt/victronenergy/dbus-systemcalc-py/delegates/dvcc.py", line 86, in _set_path
2018-04-10 14:37:36.026800500     self.monitor.set_value(self.service, path, v)
2018-04-10 14:37:36.028278500   File "/opt/victronenergy/dbus-systemcalc-py/ext/velib_python/dbusmonitor.py", line 269, in set_value
2018-04-10 14:37:36.028293500     args=[wrap_dbus_value(value)])
2018-04-10 14:37:36.028299500   File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
2018-04-10 14:37:36.038733500     message, timeout)
2018-04-10 14:37:36.047786500 DBusException: org.freedesktop.DBus.Error.UnknownObject: org.freedesktop.DBus.Error.UnknownObject
```

**Comment by mpvader** [comment]
hey @izak, we now have a toast coming, that when disabling DVCC  warns that the VE.Bus systems needs to be reset.

Perhaps its good to add another toast when enabling it? About the minimum firmware versions? Or cram it into the note above, but that might prove difficult.

Some sort of system check set of rules would also be nice, that can warn about such integrity rules, but thats quite a bit some work than just the toast; I'm afraid.
