### ISSUE TITLE
mqtt-rpc: better handle VE.Direct devices with only RX

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus#370]
Devices connected with a cable that only has the RX working will show up on dbus, as vedirect-interface puts them on there with all data from the TEXT protocol. It does quit after a while, but then serial-starter just restarts it again.

But when you then run a duplist via mqtt-rpc, it doesn't show up, of course. This is obviously confusing for everyone.

This was seen on 25705, Venus v2.20.

Most probably this is because they are using a Non-Victron USB-Serial cable; for which the TX isn't working or wired: when running vedirect-interface, the only paths that contain data are the ones that come from the text protocol. And; when requesting a VREG using the VREG interface, it fails:
```
## Normal tty does work.
root@beaglebone:~# dbus -y com.victronenergy.solarcharger.ttyO2 /Devices/0/VregLink GetVreg %0x100
data = [0, 89, 160, 255]

## USB tty does not work.
root@beaglebone:~# dbus -y com.victronenergy.solarcharger.ttyUSB1 /Devices/0/VregLink GetVreg %0x100
Traceback (most recent call last):
  File "/usr/bin/dbus", line 364, in <module>
    ret = obj.object.get_dbus_method(method.name, iface.name)(*args)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
root@beaglebone:~# 
```

vedirect-interface is being restarted all the time:
```
cat /log/serial-starter/* |tai64nlocal | grep vedirect-interface.ttyUSB1
[snip]
2018-10-19 00:31:27.736631500 INFO: Start service vedirect-interface.ttyUSB1 once
2018-10-19 00:37:02.724923500 INFO: Start service vedirect-interface.ttyUSB1 once
2018-10-19 00:38:09.319335500 INFO: Start service vedirect-interface.ttyUSB1 once
2018-10-19 00:43:22.791834500 INFO: Start service vedirect-interface.ttyUSB1 once
2018-10-19 00:51:38.030961500 INFO: Start service vedirect-interface.ttyUSB1 once
2018-10-19 00:52:24.930802500 INFO: Start service vedirect-interface.ttyUSB1 once
2018-10-19 00:55:19.333690500 INFO: Start service vedirect-interface.ttyUSB1 once
2018-10-19 00:58:45.811749500 INFO: Start service vedirect-interface.ttyUSB1 once
[snip]
```

Non original VE.Direct cable:
```
root@beaglebone:~# lsusb -v -s 2:7

Bus 002 Device 007: ID 0403:6001 Future Technology Devices International, Ltd FT232 Serial (UART) IC
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x0403 Future Technology Devices International, Ltd
  idProduct          0x6001 FT232 Serial (UART) IC
  bcdDevice            4.00
  iManufacturer           1 FTDI
  iProduct                2 USB <-> Serial
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           32
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower               90mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass    255 Vendor Specific Subclass
      bInterfaceProtocol    255 Vendor Specific Protocol
      iInterface              2 USB <-> Serial
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0000
  (Bus Powered)
```

### All the details which were written down before we found above root cause:

- dup does find the VE.Direct devices on the local serial ports.
- dup does not find any of the VE.Direct devices on the USB connected serial ports (there are 5).
- vedirect-interface does work fine with all of them

First check that nothing else is using the port:
```
root@beaglebone:~# ps | grep USB1
 2147 root      1580 S    supervise gps-dbus.ttyUSB1
 2180 root      1724 S    multilog t s99999 n8 /var/log/gps-dbus.ttyUSB1
 2378 root      1580 S    supervise vedirect-interface.ttyUSB1
 2447 root      1724 S    multilog t s99999 n8 /var/log/vedirect.ttyUSB1
28085 root      2244 S    grep USB1
```

The failure:
```
root@beaglebone:~# dup -s /dev/ttyUSB1 -v -d
VE.Direct Updater
000.001 INF.dup: start
000.002 INF.devicefinder: checking port /dev/ttyUSB1
000.005 INF.serial: port open
000.007 INF.serial: thread start
000.032 INF.hex_proto: hex: ping
000.036 INF.serial: invalid TEXT checksum received, ignoring
No VE.Direct ping reply.
002.537 WRN.serial: serial port error [system]: Operation canceled (125)
002.537 INF.serial: thread stopped
No devices were found.
Make sure the devices are switched on and connected properly.
002.540 INF.dup: done in 002.540
```

Above solar charger is a SmartSolarCharger MPPT 150/100 rev2 fw v1.30.

For reference, a successful run on the built-in ttys looks like this:
```
root@beaglebone:~# dup -s /dev/ttyO4 -v -d
VE.Direct Updater
000.001 INF.dup: start
000.002 INF.devicefinder: checking port /dev/ttyO4
000.004 INF.serial: port open
000.005 INF.serial: thread start
000.030 INF.hex_proto: hex: ping
000.038 INF.hex_proto: hex: get device id
000.046 INF.devicefinder: found BMV (PID=0x0203)
000.046 INF.hex_proto: hex: get register (0x0032)
000.074 INF.hex_proto: hex: get register (0x010B)
000.094 INF.devicefinder: internal model name="BMV-700"
000.094 INF.hex_proto: hex: get register (0x0031)
000.129 INF.hex_proto: hex: get register (0x010A)
000.175 INF.devicefinder: internal serial number="HQ1750KGK8L"
000.176 WRN.serial: serial port error [system]: Bad file descriptor (9)
000.177 INF.serial: thread stopped

| port  | serial                       | mode | id   | description                      | version  |
| /dev/ttyO4 | HQ1750KGK8L                  | APP  | 203  | BMV-700                          | 3.08     |
```

**Comment by ThiemoVanEngelen** [comment]
Fix is included in vedirect-interface 3.28, which is on the todo to be included in Venus v2.30~28.
