### ISSUE TITLE
canvu: digital input is not working

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#428]
- [x] Add dbus-digitalinputs as a machine dependency to [packagegroup-ve-dbus-data-producers.bb](https://github.com/victronenergy/meta-victronenergy/blob/master/meta-ve-software/recipes-packagegroups/packagegroup-ve-dbus-data-producers.bb) for the canvu
- [x] Fix below error

```
root@canvu500:/opt/victonenergy# ./dbus_digitalinputs.py /dev/gpio/digital_input_*
Registering GPIO 1 for type 0
Registering GPIO 1 for type 2
Traceback (most recent call last):
  File "./ext/velib_python/vedbus.py", line 313, in _properties_changed_handler
    self._eventCallback(self._serviceName, self._path, changes)
  File "./ext/velib_python/settingsdevice.py", line 107, in handleChangedSetting
    self._eventCallback(setting, oldvalue, changes['Value'])
  File "./dbus_digitalinputs.py", line 415, in handle_setting_change
    register_gpio(inputs[inp], inp, bus, settings)
  File "./dbus_digitalinputs.py", line 397, in register_gpio
    handler.level = pulses.register(path, gpio)
  File "./dbus_digitalinputs.py", line 96, in register
    with open(os.path.join(path, 'edge'), 'ab') as fp:
IOError: [Errno 13] Permission denied: '/sys/devices/soc0/soc/2100000.aips-bus/21f0000.serial/serial0/serial0-0/gpiochip7/gpio/gpio257/edge'
```

The error only occurs after going into the menus and changing the type from disabled (= type 0) to anything else.

**Comment by mansr** [comment]
Fixed in linux-canvu500 v4.14.71-canvu500-6.
