### ISSUE TITLE
dbus-cgwacs: Segfaults on exit when it finds no meter

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#435]
```
$ ./dbus-cgwacs --dbus session -s /dev/ttyUSB0 
INFO  dbus-cgwacs v1.8.8 started 
INFO  Built with Qt 5.9.5 running on 5.9.5 
INFO  Built on Mar 12 2019 at 12:41:24 
INFO  Connecting to "/dev/ttyUSB0" 
INFO  Wait for local settings on DBus...  
INFO  Local settings found 
Segmentation fault (core dumped)
```

This does not impede proper operation. It happens only when it can't find a meter, and it terminates as it should. It simply indicates a memory handling issue (possible free-ing something twice) that we might want to look at.

**Comment by izak** [comment]
```
(gdb) bt
#0  0x00007ffff7bae8a6 in QDBusMetaType::typeToSignature(int) ()
   from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#1  0x00007ffff7ba532c in qDBusParametersForMethod(QList<QByteArray> const&, QVector<int>&, QString&) () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#2  0x00007ffff7ba58fe in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#3  0x00007ffff7b693c2 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#4  0x00007ffff7b69f56 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#5  0x00007ffff7b6a3dc in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#6  0x00007ffff7b625eb in QDBusConnection::disconnect(QString const&, QString const&, QString const&, QString const&, QObject*, char const*) () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#7  0x00005555555715ec in VeQItemDbus::~VeQItemDbus (this=0x5555557ef130, __in_chrg=<optimized out>)
    at ext/velib/src/qt/ve_qitems_dbus.cpp:26
#8  0x000055555557169a in VeQItemDbus::~VeQItemDbus (this=0x5555557ef130, __in_chrg=<optimized out>)
    at ext/velib/src/qt/ve_qitems_dbus.cpp:29
#9  0x00007ffff747b19b in QObjectPrivate::deleteChildren() ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff74849cb in QObject::~QObject() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00005555555673cc in VeQItem::~VeQItem (this=0x5555557eed10, __in_chrg=<optimized out>)
    at ext/velib/src/qt/ve_qitem.cpp:19
#12 0x0000555555571662 in VeQItemDbus::~VeQItemDbus (this=0x5555557eed10, __in_chrg=<optimized out>)
    at ext/velib/src/qt/ve_qitems_dbus.cpp:23
#13 0x000055555557169a in VeQItemDbus::~VeQItemDbus (this=0x5555557eed10, __in_chrg=<optimized out>)
    at ext/velib/src/qt/ve_qitems_dbus.cpp:29
---Type <return> to continue, or q <return> to quit---
#14 0x00007ffff747b19b in QObjectPrivate::deleteChildren() ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff74849cb in QObject::~QObject() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00005555555673cc in VeQItem::~VeQItem (this=0x5555557ee800, __in_chrg=<optimized out>)
    at ext/velib/src/qt/ve_qitem.cpp:19
#17 0x0000555555571662 in VeQItemDbus::~VeQItemDbus (this=0x5555557ee800, __in_chrg=<optimized out>)
    at ext/velib/src/qt/ve_qitems_dbus.cpp:23
#18 0x000055555557169a in VeQItemDbus::~VeQItemDbus (this=0x5555557ee800, __in_chrg=<optimized out>)
    at ext/velib/src/qt/ve_qitems_dbus.cpp:29
#19 0x00007ffff747b19b in QObjectPrivate::deleteChildren() ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007ffff74849cb in QObject::~QObject() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00005555555673cc in VeQItem::~VeQItem (this=0x5555557e1b00, __in_chrg=<optimized out>)
    at ext/velib/src/qt/ve_qitem.cpp:19
#22 0x0000555555571662 in VeQItemDbus::~VeQItemDbus (this=0x5555557e1b00, __in_chrg=<optimized out>)
    at ext/velib/src/qt/ve_qitems_dbus.cpp:23
#23 0x000055555557169a in VeQItemDbus::~VeQItemDbus (this=0x5555557e1b00, __in_chrg=<optimized out>)
    at ext/velib/src/qt/ve_qitems_dbus.cpp:29
#24 0x00007ffff747b19b in QObjectPrivate::deleteChildren() ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007ffff74849cb in QObject::~QObject() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00005555555673cc in VeQItem::~VeQItem (this=0x5555557e4c10, __in_chrg=<optimized out>)
    at ext/velib/src/qt/ve_qitem.cpp:19
---Type <return> to continue, or q <return> to quit---
#27 0x0000555555598d0c in VeQItemLocal::~VeQItemLocal (this=0x5555557e4c10, 
    __in_chrg=<optimized out>) at .moc/../ext/velib/inc/velib/qt/ve_qitem.hpp:370
#28 0x0000555555598d28 in VeQItemLocal::~VeQItemLocal (this=0x5555557e4c10, 
    __in_chrg=<optimized out>) at .moc/../ext/velib/inc/velib/qt/ve_qitem.hpp:370
#29 0x00007ffff747b19b in QObjectPrivate::deleteChildren() ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007ffff74849cb in QObject::~QObject() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00005555555673cc in VeQItem::~VeQItem (this=0x5555557c7240 <VeQItems::getRoot()::theRoot>, 
    __in_chrg=<optimized out>) at ext/velib/src/qt/ve_qitem.cpp:19
#32 0x00007ffff6656041 in __run_exit_handlers (status=0, listp=0x7ffff69fe718 <__exit_funcs>, 
    run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#33 0x00007ffff665613a in __GI_exit (status=<optimized out>) at exit.c:139
#34 0x00007ffff6634b9e in __libc_start_main (main=0x555555591d14 <main(int, char**)>, argc=7, 
    argv=0x7fffffffdf78, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffdf68) at ../csu/libc-start.c:344
#35 0x000055555556264a in _start ()
```

**Comment by izak** [comment]
Only happens on PC, not on ARM. Not important enough to waste time on.
