### ISSUE TITLE
VregLink: stuck after requesting 0xEDD5 on BMV 

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#445]
After requesting 0xEDD5, which is not for a BMV at all, vedirect-interface doesn't accept any other requests on VregLink.

Why did I try requesting a non-support VREG in the first place? because I'm  working on CI & VREG testing; and part of that is making a request for each and every VREG that we have defined; 

```
root@beaglebone:~/mva# dbus -y com.victronenergy.battery.ttyO4 /Devices/0/VregLink GetVreg %0x0001
error = 33024
data = []

root@beaglebone:~/mva# dbus -y com.victronenergy.battery.ttyO4 /Devices/0/VregLink GetVreg %0xEDD5
Traceback (most recent call last):
  File "/usr/bin/dbus", line 364, in <module>
    ret = obj.object.get_dbus_method(method.name, iface.name)(*args)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

root@beaglebone:~/mva# dbus -y com.victronenergy.battery.ttyO4 /Devices/0/VregLink GetVreg %0x0001
Traceback (most recent call last):
  File "/usr/bin/dbus", line 364, in <module>
    ret = obj.object.get_dbus_method(method.name, iface.name)(*args)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

### svc -t makes it work again:

root@beaglebone:~/mva# svc -t /service/vedirect-interface.ttyO4

root@beaglebone:~/mva# dbus -y com.victronenergy.battery.ttyO4 /Devices/0/VregLink GetVreg %0x0001
error = 33024
data = []
```

**Comment by mpvader** [comment]
Hey Izak; you made that vreglink; right? In case you need any help wrt BMVs, contact Ruud.

**Comment by mpvader** [comment]
Above was seen on a BMV712_SMART; on the octo I'm using for CI testing; 192.168.4.119. Don't delete the data partition; thanks.
