### ISSUE TITLE
mqtt-rpc: Remote VEconfigure stops working after sending the same rvsc file multiple times

### ISSUE THREAD

**Issue by vejpasop** [victronenergy/venus#527]
Venus V2.40~38

Uploading the same Remote VeConfigure file multiple times (~6 times) causes a very long intermediate file to  be created in the vrm files cache.  This in could case remote ve configure to stop working until the Venus device is rebooted.

After such crash downloading the vebus configuration results in the following message.  

![afbeelding](https://user-images.githubusercontent.com/10847324/68202729-887bd300-ffc4-11e9-9ffa-340ef95a83d6.png)

Maybe sending the same file  (same checksum) over and over is not a real use case. (Note: I use it for testing during development), crashes should not result in the remote ve configure functionality to stop working.

log:

```2019-11-04 15:49:04.034277500 INFO:__main__:Starting filedownload response
2019-11-04 15:49:04.160112500 INFO:file_mgmt:Chunk 0 acked by remote. That makes for the complete file.
2019-11-04 15:49:04.162749500 INFO:file_mgmt:FileSender object done, marking as expired
2019-11-04 15:49:14.999168500 INFO:__main__:Fileupload announce received. Starting file receiver
2019-11-04 15:49:15.019500500 INFO:file_mgmt:File ca3236c785f76f42f92cf94bfbde1c2e.rvsc (ca3236c785f76f42f92cf94bfbde1c2e) already exists, cancelling upload
2019-11-04 15:49:15.021708500 INFO:__main__:Starting fileupload response
2019-11-04 15:49:15.034265500 INFO:__main__:Finished fileupload response after 1 messages
2019-11-04 15:49:15.115640500 INFO:__main__:vebusremoteconfig received
2019-11-04 15:49:15.342478500 INFO:__main__:Starting mk2VscThread
2019-11-04 15:49:15.394733500 INFO:vrmmk2vsc:write_settings from file /data/vrmfilescache/ca3236c785f76f42f92cf94bfbde1c2e_ca3236c785f76f42f92cf94bfbde1c2e_ca3236c785f76f42f92cf94bfbde1c2e_ca3236c785f76f42f92cf94bfbde1c2e_ca3236c785f76f42f92cf94bfbde1c2e_ca3236c785f76f42f92cf94bfbde1c2e_ca3236c785f76f42f92cf94bfbde1c2e.rvsc
2019-11-04 15:49:15.724160500 INFO:__main__:Starting vebusremoteconfig response
2019-11-04 15:49:52.268344500 Exception in thread mk2VscThread:
2019-11-04 15:49:52.268362500 Traceback (most recent call last):
2019-11-04 15:49:52.268369500   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
2019-11-04 15:49:52.268377500     self.run()
2019-11-04 15:49:52.268382500   File "/opt/victronenergy/mqtt-rpc/mqtt-rpc.py", line 494, in run
2019-11-04 15:49:52.268389500     md5_hash = file_mgmt.induct(self.fileName)
2019-11-04 15:49:52.268396500   File "/opt/victronenergy/mqtt-rpc/file_mgmt.py", line 38, in induct
2019-11-04 15:49:52.268547500     os.rename(s, os.path.join(FILE_LOCATION, h + '_' + filename))
2019-11-04 15:49:52.268556500 OSError: [Errno 36] File name too long
```
Note:  Sometimes after multiple transmissions of the same file mk2vsc refuses the file before the OSError 36.  If this is the case the mqtt-rpc mk2vscThread does not remain locked and dowloading configuration keeps working. In this case the upload exits with
![afbeelding](https://user-images.githubusercontent.com/10847324/68204421-405eaf80-ffc8-11e9-8bf2-54335087a105.png)

**Comment by izak** [comment]
I fixed this as part of the vebus firmware update project.
