### ISSUE TITLE
gui does not exit when OOM

### ISSUE THREAD

**Issue by jhofstee** [victronenergy/venus#727]
Found on https://vrm.victronenergy.com/installation/73940/diagnostics

```
2020-11-07 14:08:41.412412500 unknown service com.victronenergy.generator.startstop0
2020-11-07 14:08:59.225704500 out of memory, exit
2020-11-07 14:08:59.852858500 [VeQItemDbusPublisher] Unregistered service "debug.victronenergy.gui" 
```

The process ends up hanging in:
```
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
0xb609b9d0 in pthread_cond_wait () from /lib/libpthread.so.0
(gdb) bt
#0  0xb609b9d0 in pthread_cond_wait () from /lib/libpthread.so.0
#1  0xb5338950 in ?? () from /usr/lib/libdbus-1.so.3
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by jhofstee** [comment]
not always it seems:

```
2020-11-09 08:18:39.929749500 INFO  ScreenSaver::screenOff 
2020-11-09 13:16:49.472521500 out of memory, exit
2020-11-09 13:16:49.921860500 [VeQItemDbusPublisher] Unregistered service "debug.victronenergy.gui" 
2020-11-09 13:16:50.395745500 *** Starting gui ***
```
