### ISSUE TITLE
dbus-recorder: Add unicode capability

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#825]
At the moment, dbus-recorder breaks if GetText returns something outside US-ASCII.

```
# python dbusrecorder.py --record com.victronenergy.vebus.ttyUSB1 --file /tmp/rec/vebus.dat
Traceback (most recent call last):
  File "dbusrecorder.py", line 412, in <module>
    main(sys.argv[1:])
  File "dbusrecorder.py", line 410, in main
    run()
  File "dbusrecorder.py", line 337, in run
    record()
  File "dbusrecorder.py", line 211, in record
    values = device.getValues()
  File "/opt/victronenergy/dbus-recorder/dbusdevice.py", line 50, in getValues
    properties['Text'] = str(self._dbus_conn.call_blocking(self._dbus_name, i, None, 'GetText', '', []))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb0' in position 5: ordinal not in range(128)
```

This typically happens when a temperature sensor on a Multi returns `°C` as part of the returned text.

**Comment by jhofstee** [comment]
There is another one in play.py:

```
root@ccgx:~# dbus -y com.victronenergy.grid.cgwacs_ttyUSB0_di30_mb1 /CustomName SetValue 'ẞ'
Traceback (most recent call last):
  File "/usr/bin/dbus", line 379, in <module>
    ret = obj.object.get_dbus_method(method.name, iface.name)(*args)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 147, in __call__
    **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.UnicodeEncodeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dbus/service.py", line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/opt/victronenergy/dbus-recorder/play.py", line 89, in SetValue
    self._properties['Text'] = str(value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u1e9e' in position 0: ordinal not in range(128)
```
Change that to unicode() and it will start working for python2. Not sure we should do that though, switching to python3 will fix it as well.
