### ISSUE TITLE
vrmlogger crash on name lookups

### ISSUE THREAD

**Issue by izak** [victronenergy/venus#840]
```
2021-08-04 02:07:53.077596500 AttributeError: 'ConnectionError' object has no attribute 'message'
2021-08-04 02:07:53.077651500 
2021-08-04 02:07:53.077652500 During handling of the above exception, another exception occurred:
2021-08-04 02:07:53.077655500 
2021-08-04 02:07:53.077678500 Traceback (most recent call last):
2021-08-04 02:07:53.077925500   File "/opt/victronenergy/vrmlogger/http_endpoint.py", line 564, in _worker
2021-08-04 02:07:53.077928500     self._worker_inner(logurl, interval)
2021-08-04 02:07:53.077955500   File "/opt/victronenergy/vrmlogger/http_endpoint.py", line 601, in _worker_inner
2021-08-04 02:07:53.077959500     result = self._send_jobs_to_vrm(job, vrmhttp)
2021-08-04 02:07:53.077982500   File "/opt/victronenergy/vrmlogger/http_endpoint.py", line 637, in _send_jobs_to_vrm
2021-08-04 02:07:53.077985500     result, error, msg = vrmhttp.send_raw_bulk_to_vrm(compressed_data, crc32)
2021-08-04 02:07:53.078008500   File "/opt/victronenergy/vrmlogger/vrmhttp.py", line 217, in send_raw_bulk_to_vrm
2021-08-04 02:07:53.078012500     exs = str(ex.message)
2021-08-04 02:07:53.078082500 AttributeError: 'ConnectionError' object has no attribute 'message'
2021-08-04 02:07:53.098748500 *** starting vrmlogger ***
```

**Comment by izak** [comment]
The issue is that in several places exception handling attempts to access the `.message` property of the exception. This is a python2 aberration that can in most cases be replaced by `str(exception)`.
